### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [tnwinc/SublimePigLatin#3]
I would like to use your grammar for PigLatin but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by chrisbreiding** [comment]
That's cool you're interested in using my code. I'll put it under the MIT license. Once I get home, I'll add it to the repo and make it official. If you can, let me know what you create with it. I'd be interested to see.

**Comment by pchaigno** [comment]
Thanks!
